spring:
  application:
    name: PayFlow

  datasource:
    url: jdbc:postgresql://localhost:5432/payflow
    username: payflow
    password: payflow

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      username: ${REDIS_USERNAME:}
      password: ${REDIS_PASSWORD:}
      ssl:
        enabled: ${REDIS_SSL:false}

jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000

server:
  port: ${PORT:8080}