spring:
  application:
    name: PayFlow

  datasource:
    url: jdbc:postgresql://pay-flow-venkateshpentakota147-65fa.l.aivencloud.com:17503/defaultdb?sslmode=require
    username: avnadmin
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
jwt:
  secret: {JWT_SECRET}
  expiration: 3600000
server:
  port: ${PORT:8080}